### ISSUE TITLE
Change Travis-CI integration to just flake8 checking

### ISSUE THREAD

**Issue by davehunt** [mozilla/bidpom#90]
Update the Travis-CI config to just do basic code checking. In order to do this, we need to change `.travis.yml` to look as follows:

```yml
language: python
python: 2.7
install: "pip install flake8"
script: "flake8 ."
```

Also, create a `setup.cfg` file to configure `flake8` that is the same as https://github.com/mozilla/mcom-tests/blob/master/setup.cfg
